aspProj/WebApp/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain.App;

namespace WebApp.Controllers
{
    /// <summary>
    /// CartsController api
    /// </summary>
    public class CartsController : Controller
    {
        private readonly AppDbContext _context;

        /// <summary>
        /// CartsController context
        /// </summary>
        /// <param name="context"></param>
        public CartsController(AppDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Get Carts
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Carts.Include(c => c.AppUser);
            return View(await appDbContext.ToListAsync());
        }
        
        /// <summary>
        /// GET: Carts/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        /// <summary>
        /// Carts Create
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Cart Create
        /// </summary>
        /// <param name="cart"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                cart.Id = Guid.NewGuid();
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", cart.AppUserId);
            return View(cart);
        }

        /// <summary>
        /// Cart edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", cart.AppUserId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Cart Edit
        /// </summary>
        /// <param name="id"></param>
        /// <param name="cart"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", cart.AppUserId);
            return View(cart);
        }

        /// <summary>
        /// Cart delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        /// <summary>
        /// POST: Carts/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cart = await _context.Carts.FindAsync(id);
            _context.Carts.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(Guid id)
        {
            return _context.Carts.Any(e => e.Id == id);
        }
    }
}

aspProj/WebApp/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain.App;

namespace WebApp.Controllers
{
    /// <summary>
    /// ItemsController api
    /// </summary>
    public class ItemsController : Controller
    {
        private readonly AppDbContext _context;

        /// <summary>
        /// ItemsController context
        /// </summary>
        /// <param name="context"></param>
        public ItemsController(AppDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// GET: Items
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Items.Include(i => i.AppUser).Include(i => i.DetailedCategory).Include(i => i.ItemQuality).Include(i => i.ItemStatus).Include(i => i.Location).Include(i => i.MainCategory);
            return View(await appDbContext.ToListAsync());
        }

        /// <summary>
        /// GET: Items/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.AppUser)
                .Include(i => i.DetailedCategory)
                .Include(i => i.ItemQuality)
                .Include(i => i.ItemStatus)
                .Include(i => i.Location)
                .Include(i => i.MainCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        /// <summary>
        /// GET: Items/Create
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName");
            ViewData["DetailedCategoryId"] = new SelectList(_context.DetailedCategories, "Id", "DetailedCategoryName");
            ViewData["ItemQualityId"] = new SelectList(_context.ItemQualities, "Id", "QualityName");
            ViewData["ItemStatusId"] = new SelectList(_context.ItemStatuses, "Id", "StatusName");
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "LocationName");
            ViewData["MainCategoryId"] = new SelectList(_context.MainCategories, "Id", "MainCategoryName");
            return View();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// POST: Items/Create
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemName,YearMade,ItemDescription,Price,LocationId,ItemQualityId,ItemStatusId,DetailedCategoryId,MainCategoryId,AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Item item)
        {
            if (ModelState.IsValid)
            {
                item.Id = Guid.NewGuid();
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", item.AppUserId);
            ViewData["DetailedCategoryId"] = new SelectList(_context.DetailedCategories, "Id", "DetailedCategoryName", item.DetailedCategoryId);
            ViewData["ItemQualityId"] = new SelectList(_context.ItemQualities, "Id", "QualityName", item.ItemQualityId);
            ViewData["ItemStatusId"] = new SelectList(_context.ItemStatuses, "Id", "StatusName", item.ItemStatusId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "LocationName", item.LocationId);
            ViewData["MainCategoryId"] = new SelectList(_context.MainCategories, "Id", "MainCategoryName", item.MainCategoryId);
            return View(item);
        }

        /// <summary>
        /// GET: Items/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", item.AppUserId);
            ViewData["DetailedCategoryId"] = new SelectList(_context.DetailedCategories, "Id", "DetailedCategoryName", item.DetailedCategoryId);
            ViewData["ItemQualityId"] = new SelectList(_context.ItemQualities, "Id", "QualityName", item.ItemQualityId);
            ViewData["ItemStatusId"] = new SelectList(_context.ItemStatuses, "Id", "StatusName", item.ItemStatusId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "LocationName", item.LocationId);
            ViewData["MainCategoryId"] = new SelectList(_context.MainCategories, "Id", "MainCategoryName", item.MainCategoryId);
            return View(item);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// POST: Items/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ItemName,YearMade,ItemDescription,Price,LocationId,ItemQualityId,ItemStatusId,DetailedCategoryId,MainCategoryId,AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "FirstName", item.AppUserId);
            ViewData["DetailedCategoryId"] = new SelectList(_context.DetailedCategories, "Id", "DetailedCategoryName", item.DetailedCategoryId);
            ViewData["ItemQualityId"] = new SelectList(_context.ItemQualities, "Id", "QualityName", item.ItemQualityId);
            ViewData["ItemStatusId"] = new SelectList(_context.ItemStatuses, "Id", "StatusName", item.ItemStatusId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "LocationName", item.LocationId);
            ViewData["MainCategoryId"] = new SelectList(_context.MainCategories, "Id", "MainCategoryName", item.MainCategoryId);
            return View(item);
        }

        /// <summary>
        /// GET: Items/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.AppUser)
                .Include(i => i.DetailedCategory)
                .Include(i => i.ItemQuality)
                .Include(i => i.ItemStatus)
                .Include(i => i.Location)
                .Include(i => i.MainCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        /// <summary>
        /// POST: Items/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(Guid id)
        {
            return _context.Items.Any(e => e.Id == id);
        }
    }
}

aspProj/WebApp/Views/Shared/_LanguageSelection.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@{
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new {Value = c.Name, Text = c.NativeName}).ToList();
}

<li class="nav-item dropdown">
    <a class="nav-link text-dark dropdown-toggle" href="javascript:{}" id="navbarLangDropdown" role="button" data-toggle="dropdown">Language</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarLangDropdown">
        @foreach (var item in cultureItems)
        {
            <a class="dropdown-item text-dark"
               asp-area="" asp-controller="Home" asp-action="SetLanguage" asp-route-culture="@item.Value"
               asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                @item.Text
            </a>
        }
    </div>
</li>

aspProj/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    @*
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
        *@
        
        <link rel="stylesheet" href="~/dist/site.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Resources.Views.Shared._Layout.Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Resources.Views.Shared._Layout.Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">@Resources.Views.Shared._Layout.Items</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">@Resources.Views.Shared._Layout.Carts</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comments" asp-action="Index">@Resources.Views.Shared._Layout.Comments</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryTypes" asp-action="Index">@Resources.Views.Shared._Layout.DeliveryTypes</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="DetailedCategories" asp-action="Index">@Resources.Views.Shared._Layout.DetailedCategories</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ItemQualities" asp-action="Index">@Resources.Views.Shared._Layout.ItemQualities</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">@Resources.Views.Shared._Layout.Items</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ItemStatuses" asp-action="Index">@Resources.Views.Shared._Layout.ItemStatuses</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">@Resources.Views.Shared._Layout.Locations</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="MainCategories" asp-action="Index">@Resources.Views.Shared._Layout.MainCategories</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">@Resources.Views.Shared._Layout.Orders</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="PaymentMethods" asp-action="Index">@Resources.Views.Shared._Layout.PaymentMethods</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pictures" asp-action="Index">@Resources.Views.Shared._Layout.Pictures</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ratings" asp-action="Index">@Resources.Views.Shared._Layout.Ratings</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="LangStrTranslations" asp-action="Index">@Resources.Views.Shared._Layout.Translations</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="LangStrs" asp-action="Index">LangStrs</a>
                        </div>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/dist/site.js" asp-append-version="true"></script>
<script src="~/dist/jquery.validate.globalize.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)

@{    
	var currentCultureCode = Thread.CurrentThread.CurrentCulture.Name.Split('-')[0];

    // map .net datetime format strings to flatpick/momentjs format
    
    // https://flatpickr.js.org/formatting/
    // d - day of month,2 digits
    // j - day of month, no leading zero
    // m - month, 2 digits
    // n - mont, no leading zero
    // y - 2 digit year, Y - 4 digit year
    
    // https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo?view=netcore-3.1
    // dd.MM.yyyy or dd/MM/yyyy
    
    var datePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortDatePattern;
    datePattern = datePattern
        .Replace("dd", "d")
        .Replace("MM", "m")
        .Replace("yyyy", "Y");

    // LongTimePattern and ShortTimePattern HH:mm for 23:59,  h:mm tt for 11:59 PM
    var timePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortTimePattern;
    var clock24H = timePattern.Contains("tt") == false;
    timePattern = timePattern
        .Replace("HH", "H")
        .Replace("mm", "i")
        .Replace("ss", "S")
        .Replace("tt", "K");
    var dateTimePattern = timePattern + " " + datePattern;
}
<script>
    // https://github.com/globalizejs/globalize#installation
    $.when(
        $.get("/dist/cldr-core/supplemental/likelySubtags.json"),
        $.get("/dist/cldr-core/supplemental/numberingSystems.json"),
        $.get("/dist/cldr-core/supplemental/timeData.json"),
        $.get("/dist/cldr-core/supplemental/weekData.json"),
        
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/numbers.json"),
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/currencies.json"),
        
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-generic.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-gregorian.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/dateFields.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/timeZoneNames.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });
    }).then(
        Globalize.load
    ).then(function () {
        // Initialise Globalize to the current culture
        Globalize.locale('@currentCultureCode');
    });
    
    $(function () {
        $('[type="datetime-local"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
		        locale: "@currentCultureCode",
		        enableTime: true,
	    	    altFormat: "@dateTimePattern",
	    	    altInput: true,
	    	    dateFormat: "Z", // iso format
	    	    disableMobile: true,
	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="time"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
	    	    locale: "@currentCultureCode",
	    	    enableTime: true,
	    	    noCalendar: true,

	    	    altFormat: "@timePattern",
	    	    altInput: true,
	    	    dateFormat: "H:i", // 24h HH:mm
	    	    disableMobile: true,

	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="date"]').each(function (index, value) {
		    $(value).attr('type', 'text');
		    $(value).val(value.defaultValue);
		    $(value).flatpickr({
    		    locale: "@currentCultureCode",
	    	    altFormat: "@datePattern",
	    	    altInput: true,
                disableMobile: true,
	    	    dateFormat: "Y-m-d", // YYYY-MM-DD
		    });
        });
    });
</script>
</body>
</html>